name: WahooFitToGarmin.CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@master

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release  
      workdir: './Sources'

    - name: Upload build results
      uses: actions/upload-artifact@v2
      with:
        name: 'WahooFitToGarmin'
        path: ${{ github.workspace }}/Sources/bin/Release/net5.0/
    
    - name: Publish      
      run: dotnet publish -c Release

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Sources/Dockerfile
        push: true
        tags: banzzouille/wahoo-fit-to-garmin
